# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "admins", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "first_name", :string, :limit => 100, :default => "", :null => false
    t.column "last_name", :string, :limit => 100, :default => "", :null => false
    t.column "email", :string, :limit => 100, :default => "", :null => false
    t.column "password", :string, :limit => 32
    t.column "confirmed", :enum, :limit => [:y]
  end

  add_index "admins", ["guid"], :name => "guid", :unique => true
  add_index "admins", ["email"], :name => "email", :unique => true

  create_table "album_photos", :force => true do |t|
    t.column "student_photo_album_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "caption", :string, :limit => 500
  end

  add_index "album_photos", ["guid"], :name => "guid", :unique => true

  create_table "articles", :force => true do |t|
    t.column "title", :string
    t.column "content", :text
    t.column "created_on", :datetime
  end

  create_table "attribute_category_maps", :force => true do |t|
    t.column "classified_category_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "generic_attribute_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "attribute_index", :integer
  end

  create_table "attribute_validities", :force => true do |t|
    t.column "generic_attribute_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "valid_value", :string, :limit => 100
    t.column "min_range", :float, :default => 0.0
    t.column "max_range", :float, :default => 0.0
  end

  create_table "category_tree_nodes", :force => true do |t|
    t.column "parent_id", :integer
    t.column "lft", :integer
    t.column "rgt", :integer
    t.column "classified_category_id", :integer, :limit => 10
  end

  add_index "category_tree_nodes", ["classified_category_id"], :name => "classified_category_id", :unique => true

  create_table "change_name_requests", :force => true do |t|
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "requested_name", :string, :limit => 200, :default => "", :null => false
    t.column "created_on", :timestamp
  end

  create_table "classified_categories", :force => true do |t|
    t.column "name", :string, :limit => 100
    t.column "select_name", :string, :limit => 100
  end

  add_index "classified_categories", ["name"], :name => "name", :unique => true

  create_table "classified_post_replies", :force => true do |t|
    t.column "post_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "replyer_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "subject", :string, :limit => 100
    t.column "reply", :string, :limit => 3000
    t.column "created_on", :datetime, :null => false
  end

  create_table "classified_posts", :force => true do |t|
    t.column "classified_category_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "description", :text
    t.column "poster_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "network_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "school_id", :integer, :limit => 10
    t.column "created_on", :datetime, :null => false
    t.column "updated_on", :datetime, :null => false
  end

  create_table "countries", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
  end

  create_table "course_notes", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "course_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "klass_id", :integer, :limit => 10
    t.column "owner_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "note_type", :enum, :limit => [:"lecture note", :exam, :assignment, :"term paper", :"term project"], :null => false
    t.column "anonymous", :enum, :limit => [:y]
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "comment", :string, :limit => 500
    t.column "num_downloads", :integer, :default => 0
    t.column "created_on", :datetime, :null => false
  end

  add_index "course_notes", ["guid"], :name => "guid", :unique => true

  create_table "course_subjects", :force => true do |t|
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "code", :string, :limit => 30, :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
  end

  add_index "course_subjects", ["code", "school_id"], :name => "code", :unique => true

  create_table "courses", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "course_subject_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "subject", :string, :limit => 30
    t.column "number", :string, :limit => 10, :default => "", :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "credit", :float, :limit => 10, :default => 0.0
    t.column "description", :string, :limit => 5000
  end

  add_index "courses", ["guid"], :name => "guid", :unique => true
  add_index "courses", ["course_subject_id", "number", "school_id"], :name => "course_subject_id", :unique => true

  create_table "forum_threads", :force => true do |t|
    t.column "topic_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "is_header", :enum, :limit => [:y]
    t.column "poster_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "subject", :string, :limit => 100
    t.column "message", :text
    t.column "thread_replyee_id", :integer, :limit => 10
    t.column "created_on", :datetime, :null => false
  end

  create_table "forums", :force => true do |t|
    t.column "context_guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "creator_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "topic", :string, :limit => 100, :default => "", :null => false
    t.column "last_post_id", :integer, :limit => 10
    t.column "last_poster_id", :integer, :limit => 10
    t.column "last_post_time", :datetime
    t.column "num_views", :integer, :limit => 10, :default => 0
    t.column "num_posts", :integer, :limit => 10, :default => 0
    t.column "created_on", :datetime, :null => false
  end

  create_table "friend_requests", :force => true do |t|
    t.column "requester_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "requestee_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "created_on", :timestamp
    t.column "message", :string, :limit => 500
  end

  add_index "friend_requests", ["requester_id", "requestee_id"], :name => "requester_id", :unique => true

  create_table "generic_attributes", :force => true do |t|
    t.column "name", :string, :limit => 100
    t.column "_type_", :enum, :limit => [:multiple, :boolean, :currency, :text, :date, :address, :number, :multiple_with_input]
    t.column "required", :enum, :limit => [:y, :n], :default => :n
    t.column "field_length", :integer, :limit => 6
    t.column "descr", :string, :limit => 200
    t.column "blank_err", :string, :limit => 200
    t.column "format_err", :string, :limit => 200
    t.column "sortable", :enum, :limit => [:y, :n], :default => :n
    t.column "searchable", :enum, :limit => [:y, :n], :default => :y
    t.column "listable", :enum, :limit => [:y, :n], :default => :n
    t.column "check_pattern", :string, :limit => 100
    t.column "other_name", :string, :limit => 100
    t.column "field_desc", :string, :limit => 200
  end

  create_table "instructor_assesments", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "course_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "klass_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "instructor_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "rating", :integer, :limit => 6
  end

  add_index "instructor_assesments", ["guid"], :name => "guid", :unique => true
  add_index "instructor_assesments", ["student_id", "klass_id"], :name => "student_id", :unique => true

  create_table "instructors", :force => true do |t|
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "first_name", :string, :limit => 30
    t.column "last_name", :string, :limit => 30
    t.column "locked", :enum, :limit => [:y]
    t.column "updated_on", :datetime
    t.column "email_address", :string, :limit => 150, :default => "", :null => false
  end

  add_index "instructors", ["email_address"], :name => "email_address", :unique => true

  create_table "intranet_message_registries", :force => true do |t|
    t.column "intranet_message_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "reciever_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "is_read", :enum, :limit => [:y]
    t.column "folder", :enum, :limit => [:sm, :in], :default => :in, :null => false
  end

  add_index "intranet_message_registries", ["reciever_id", "intranet_message_id"], :name => "reciever_id", :unique => true

  create_table "intranet_messages", :force => true do |t|
    t.column "sender_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "subject", :string, :limit => 100
    t.column "body", :text
    t.column "deleted_by_sender", :enum, :limit => [:y]
    t.column "created_on", :timestamp
  end

  create_table "item_attribute_values", :force => true do |t|
    t.column "classified_post_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "classified_category_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "attrb_1_value", :string, :limit => 100
    t.column "attrb_2_value", :string, :limit => 100
    t.column "attrb_3_value", :string, :limit => 100
    t.column "attrb_4_value", :string, :limit => 100
    t.column "attrb_5_value", :string, :limit => 100
    t.column "attrb_6_value", :string, :limit => 100
    t.column "attrb_7_value", :string, :limit => 100
    t.column "attrb_8_value", :string, :limit => 100
  end

  create_table "item_reports", :force => true do |t|
    t.column "report_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "reporter_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "reason_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "comments", :string, :limit => 1000, :default => "", :null => false
    t.column "created_on", :timestamp
  end

  create_table "klass_enrollments", :force => true do |t|
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "semester_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "klass_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "course_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "created_on", :datetime, :null => false
  end

  add_index "klass_enrollments", ["student_id", "semester_id", "course_id"], :name => "student_id", :unique => true

  create_table "klass_schedules", :force => true do |t|
    t.column "klass_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "start_time", :string, :limit => 5, :default => "", :null => false
    t.column "end_time", :string, :limit => 5, :default => "", :null => false
    t.column "day_of_week", :enum, :limit => [:Monday, :Tuesday, :Wednesday, :Thursday, :Friday, :Saturday, :Sunday], :null => false
  end

  add_index "klass_schedules", ["start_time", "end_time", "day_of_week", "klass_id"], :name => "start_time", :unique => true

  create_table "klasses", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "course_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "semester_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "instructor_id", :integer, :limit => 10
    t.column "room", :string, :limit => 30
    t.column "division", :integer, :limit => 6, :default => 0, :null => false
  end

  add_index "klasses", ["guid"], :name => "guid", :unique => true

  create_table "networks", :force => true do |t|
    t.column "sub_region_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
  end

  create_table "news_events", :force => true do |t|
    t.column "context_guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "icon_url", :string, :limit => 100
    t.column "type", :string, :limit => 100
    t.column "message", :string, :limit => 500, :default => "", :null => false
    t.column "created_on", :timestamp
  end

  create_table "oycas_blogs", :force => true do |t|
    t.column "oycas_userid", :integer, :limit => 10, :default => 0, :null => false
    t.column "subject", :string, :limit => 100, :default => "", :null => false
    t.column "text", :text, :default => "", :null => false
    t.column "month_id", :string, :limit => 6
    t.column "created_on", :datetime, :null => false
  end

  create_table "popularity_rates", :force => true do |t|
    t.column "rater_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "ratee_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "rate_value", :integer, :default => 0
    t.column "created_on", :timestamp
  end

  add_index "popularity_rates", ["rater_id", "ratee_id"], :name => "rater_id", :unique => true

  create_table "post_images", :force => true do |t|
    t.column "classified_post_id", :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "project_folders", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "project_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "folder", :string, :limit => 100, :default => "", :null => false
  end

  add_index "project_folders", ["guid"], :name => "guid", :unique => true

  create_table "project_meeting_notes", :force => true do |t|
    t.column "project_meeting_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "message", :string, :limit => 1000, :default => "", :null => false
    t.column "created_on", :datetime, :null => false
  end

  create_table "project_meeting_participants", :force => true do |t|
    t.column "project_meeting_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "participant_id", :integer, :limit => 20, :default => 0, :null => false
  end

  create_table "project_meetings", :force => true do |t|
    t.column "project_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "scheduled_on", :datetime, :null => false
    t.column "created_on", :datetime, :null => false
    t.column "scheduled_by", :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "project_members", :force => true do |t|
    t.column "project_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "project_email_address", :string, :limit => 100, :default => "", :null => false
    t.column "is_activated", :enum, :limit => [:y, :n], :default => :n, :null => false
  end

  create_table "project_task_assignees", :force => true do |t|
    t.column "project_task_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "assignee_id", :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "project_tasks", :force => true do |t|
    t.column "project_id", :integer, :limit => 20, :default => 0, :null => false
    t.column "is_completed", :enum, :limit => [:y, :n], :default => :n, :null => false
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "created_on", :datetime, :null => false
    t.column "start_date", :datetime, :null => false
    t.column "completion_date", :datetime, :null => false
    t.column "task_assigner", :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "projects", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "klass_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "description", :string, :limit => 1000
    t.column "created_on", :datetime, :null => false
  end

  create_table "registrations", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "random_number", :integer, :limit => 10, :default => 0, :null => false
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "school_status", :enum, :limit => [:undergraduate, :graduate, :faculty, :staff], :default => :undergraduate
    t.column "name", :string, :limit => 220
    t.column "email", :string, :limit => 100, :default => "", :null => false
    t.column "password", :string, :limit => 100
    t.column "created_on", :timestamp
  end

  add_index "registrations", ["guid"], :name => "guid", :unique => true

  create_table "report_reasons", :force => true do |t|
    t.column "report_type_id", :integer, :default => 0, :null => false
    t.column "reason", :string, :limit => 100, :default => "", :null => false
  end

  add_index "report_reasons", ["report_type_id", "reason"], :name => "report_type_id", :unique => true

  create_table "report_types", :force => true do |t|
    t.column "item_type", :enum, :limit => [:profile, :photo, :note, :classified], :null => false
  end

  add_index "report_types", ["item_type"], :name => "item_type", :unique => true

  create_table "reported_items", :force => true do |t|
    t.column "reported_item_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10
    t.column "resolved", :enum, :limit => [:y]
    t.column "resolved_comments", :string, :limit => 500
    t.column "resolved_time", :datetime
    t.column "report_type_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "num_reports", :integer, :default => 0
    t.column "last_report_time", :datetime
  end

  create_table "school_members", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "default_school", :enum, :limit => [:y]
    t.column "confirmed", :enum, :limit => [:y]
    t.column "registered_email", :string, :limit => 100, :default => "", :null => false
  end

  add_index "school_members", ["guid"], :name => "guid", :unique => true
  add_index "school_members", ["registered_email"], :name => "registered_email", :unique => true
  add_index "school_members", ["student_id", "school_id"], :name => "student_id", :unique => true
  add_index "school_members", ["student_id", "default_school"], :name => "student_id_2", :unique => true

  create_table "school_staffs", :force => true do |t|
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "email_address", :string, :limit => 100, :default => "", :null => false
    t.column "entry_justification", :string, :default => "", :null => false
  end

  add_index "school_staffs", ["email_address", "school_id"], :name => "email_address", :unique => true

  create_table "schools", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "short_name", :string, :limit => 20, :default => "", :null => false
    t.column "network_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "city", :string, :limit => 100, :default => "", :null => false
    t.column "website", :string, :limit => 100, :default => "", :null => false
    t.column "email_domain", :string, :limit => 20, :default => "", :null => false
    t.column "time_zone", :string, :limit => 50, :default => "", :null => false
    t.column "facebook_domain", :string, :limit => 50
    t.column "active", :enum, :limit => [:y]
    t.column "updated_on", :datetime
    t.column "created_on", :datetime
    t.column "rss_news_feed", :string, :limit => 500
  end

  add_index "schools", ["guid"], :name => "guid", :unique => true
  add_index "schools", ["email_domain"], :name => "email_domain", :unique => true
  add_index "schools", ["network_id", "name"], :name => "network_id", :unique => true

  create_table "scraps", :force => true do |t|
    t.column "reciever_guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "sender_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "created_on", :timestamp
    t.column "message", :string, :limit => 500, :default => "", :null => false
  end

  create_table "seasons", :force => true do |t|
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "name", :string, :limit => 30
    t.column "start_month", :integer, :limit => 6
    t.column "end_month", :integer, :limit => 6
    t.column "season_index", :integer, :limit => 1
  end

  add_index "seasons", ["school_id", "name"], :name => "school_id", :unique => true

  create_table "semesters", :force => true do |t|
    t.column "school_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "season_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "__current__", :enum, :limit => [:Y]
    t.column "start_date", :datetime
    t.column "end_date", :datetime
    t.column "class_start", :datetime
    t.column "class_end", :datetime
    t.column "exam_end", :datetime
  end

  add_index "semesters", ["school_id", "__current__"], :name => "school_id", :unique => true

  create_table "string_counters", :force => true do |t|
    t.column "string_entry", :string, :limit => 500
    t.column "count", :integer, :limit => 5
  end

  create_table "student_contact_emails", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "contact_email", :string, :limit => 100, :default => "", :null => false
    t.column "visibility", :integer, :limit => 4, :default => 0
    t.column "confirmed", :enum, :limit => [:y]
    t.column "default_email", :enum, :limit => [:y]
  end

  add_index "student_contact_emails", ["guid"], :name => "guid", :unique => true
  add_index "student_contact_emails", ["contact_email"], :name => "contact_email", :unique => true
  add_index "student_contact_emails", ["student_id", "default_email"], :name => "student_id", :unique => true

  create_table "student_friends", :force => true do |t|
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "friend_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "created_on", :timestamp
  end

  add_index "student_friends", ["student_id", "friend_id"], :name => "student_id", :unique => true

  create_table "student_photo_albums", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
    t.column "location", :string, :limit => 100
    t.column "description", :string, :limit => 400
    t.column "album_cover", :integer, :limit => 20
    t.column "visibility", :integer, :limit => 6, :default => 0
    t.column "created_on", :datetime, :null => false
  end

  add_index "student_photo_albums", ["guid"], :name => "guid", :unique => true

  create_table "student_profiles", :force => true do |t|
    t.column "student_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "im", :string, :limit => 50, :default => ""
    t.column "im_visibility", :integer, :limit => 6, :default => 0, :null => false
    t.column "land_phone", :string, :limit => 50, :default => ""
    t.column "land_phone_visibility", :integer, :limit => 6, :default => 0, :null => false
    t.column "mobile_phone", :string, :limit => 50, :default => ""
    t.column "mobile_phone_visibility", :integer, :limit => 6, :default => 0, :null => false
    t.column "residence", :string, :limit => 50, :default => ""
    t.column "room", :string, :limit => 50, :default => ""
    t.column "residence_room_visibility", :integer, :limit => 6, :default => 0, :null => false
    t.column "address", :string, :limit => 100, :default => ""
    t.column "city", :string, :limit => 50, :default => ""
    t.column "zip_code", :string, :limit => 10, :default => ""
    t.column "address_visibility", :integer, :limit => 6, :default => 0, :null => false
    t.column "country", :string, :limit => 50
    t.column "sub_region", :string, :limit => 50
    t.column "website", :string, :limit => 200, :default => ""
    t.column "religious_views", :enum, :limit => [:Atheist, :Bahai, :Buddhist, :"Cao Dai", :"Christian/Anglican", :"Christian/Catholic", :"Christian/LDS", :"Christian/Orthodox", :"Christian/Other", :"Christian/Protestant", :Hindu, :Jain, :Jewish, :Muslim, :"Neo-Paganist", :Rastafarian, :"Religious humanism", :Scientologist, :Shinto, :Sikh, :"Spiritual but not religious", :Taoist, :Tenrikyo, :"Unitarian Universalist", :Zoroastrian, :Other]
    t.column "political_views", :enum, :limit => [:"Right-Conservative", :"Very Right-Conservative", :Centrist, :"Left-Liberal", :"Very Left-Liberal", :Libertarian, :"Very Libertarian", :Authoritarian, :"Very Authoritarian", :Depends, :"Not Political"]
    t.column "activities", :string, :limit => 300, :default => ""
    t.column "interests", :string, :limit => 300, :default => ""
    t.column "favorite_music", :string, :limit => 300, :default => ""
    t.column "favorite_tv_shows", :string, :limit => 300, :default => ""
    t.column "favorite_movies", :string, :limit => 300, :default => ""
    t.column "favorite_books", :string, :limit => 300, :default => ""
    t.column "favorite_quotes", :string, :limit => 300, :default => ""
    t.column "about_me", :string, :limit => 300, :default => ""
    t.column "personal_info_set", :enum, :limit => [:y, :n], :default => :y
  end

  add_index "student_profiles", ["student_id"], :name => "student_id", :unique => true

  create_table "students", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
    t.column "username", :string, :limit => 100, :default => "", :null => false
    t.column "rank", :enum, :limit => [:student, :dummy, :piggy], :default => :student
    t.column "school_status", :enum, :limit => [:undergraduate, :graduate, :faculty, :staff], :default => :undergraduate
    t.column "account_status", :enum, :limit => [:active, :suspended, :deactivated], :default => :active
    t.column "account_status_change_date", :datetime
    t.column "first_name", :string, :limit => 100, :default => "", :null => false
    t.column "last_name", :string, :limit => 100, :default => "", :null => false
    t.column "whole_name", :string, :limit => 220
    t.column "password", :string, :limit => 32, :default => "", :null => false
    t.column "security_question", :string, :limit => 100
    t.column "security_answer", :string, :limit => 100
    t.column "time_zone", :string, :limit => 50
    t.column "login_times", :integer, :limit => 10, :default => 0
    t.column "login_time", :datetime
    t.column "logoff_time", :datetime
    t.column "profile_image_set", :enum, :limit => [:y]
    t.column "mood_status", :string, :limit => 100
    t.column "status_updated_on", :datetime
    t.column "profile_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "current_course_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "course_archive_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "desk_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "friend_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "send_msg_option", :enum, :limit => [:y], :default => :y
    t.column "add_friend_option", :enum, :limit => [:y], :default => :y
    t.column "current_courses_option", :enum, :limit => [:y], :default => :y
    t.column "birthdate_option", :enum, :limit => [:y], :default => :y
    t.column "relationship_status_option", :enum, :limit => [:y], :default => :y
    t.column "friend_option", :enum, :limit => [:y], :default => :y
    t.column "rate_option", :enum, :limit => [:y], :default => :y
    t.column "status_option", :enum, :limit => [:y], :default => :y
    t.column "gender", :enum, :limit => [:Male, :Female]
    t.column "birthdate", :date
    t.column "birthdate_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "birthdate_show_format", :enum, :limit => [:full, :partial], :default => :full, :null => false
    t.column "sexual_orientation", :enum, :limit => [:Straight, :Gay, :"Bi-Sexual", :"Bi-Curious"]
    t.column "sexual_orientation_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "relationship_status", :enum, :limit => [:Single, :"In a relationship", :"Open Relationship", :Engaged, :Married]
    t.column "relationship_status_visibility", :integer, :limit => 6, :default => 1, :null => false
    t.column "add_friend_notification", :enum, :limit => [:y], :default => :y
    t.column "send_message_notification", :enum, :limit => [:y]
    t.column "note_upload_notification", :enum, :limit => [:y]
    t.column "school_discussion_notification", :enum, :limit => [:y]
    t.column "class_discussion_notification", :enum, :limit => [:y]
    t.column "classifieds_notification", :enum, :limit => [:y]
    t.column "avg_rate", :float, :default => 0.0
    t.column "rating", :integer, :default => 0
    t.column "votes", :integer, :default => 0
    t.column "facebook_uid", :integer, :limit => 10
    t.column "last_access_time", :datetime
  end

  add_index "students", ["guid"], :name => "guid", :unique => true
  add_index "students", ["username"], :name => "username", :unique => true
  add_index "students", ["whole_name"], :name => "whole_name"

  create_table "sub_regions", :force => true do |t|
    t.column "country_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "name", :string, :limit => 100, :default => "", :null => false
  end

  create_table "uniq_guids", :force => true do |t|
    t.column "guid", :integer, :limit => 20, :default => 0, :null => false
  end

  add_index "uniq_guids", ["guid"], :name => "guid", :unique => true

end
